- name: Create VMs
  hosts: all
  gather_facts: false
  vars:
    cloud_pass: redhat
    lab_rsa: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNB+TF+BUyIYeRVWrEauK8S4k+YLGQksbrDBzLuMzHFGGL3MedRQnhpt9tLA1/qxVNOxIqm/kto0FohMb8KaCeyA4xRwoWASzSUv9n8s1Jn5d2ic7aPbDZ50vbepeOB39IajjU4hy0wHTtuTufNW/VipqKAWVCPm+RFzGAfdFquB9MTiMwhVm1WBJMew06l5VAQA1BLmpMsz2Jbi2rTXepqGjZYdxYUhAwow8WMiQgZukY221fsmCERqDI/tz14ltB5lBtlqzSabdNlMVA/eeHzwd4GYLY9RuP/if4XSAIpA9Jbc3TUEAn4nBXywu4RjNi7CiMUZI5/Y3Ye0bb7d0CP/NuezbqlrsQSAvvu6IJs9HLxJlzaCAk4+DRVozseaKKZp0z+yLtk/Id2lQKlEZ8Hbi21Qhbu/r3zI+FaTC8jwrWffIdyRCreGBnhWZZFhJi2+zG+19eXy4Qf8IYJScPgMQUSfiQYK2f0PA92ywTVsTNyb58qLD8XIZ6xiumvT8= root@wsphost" 

  tasks:

    - name: Create labkey secret
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: labkey
            namespace: "{{ target_ns }}"
          type: Opaque
          data:
            key: "{{ lab_rsa | b64encode }}"

    - name: Create VM from template
      vars:
        j2vm_name: j2vm
        itype: u1.small
        add_net: true
      redhat.openshift.k8s:
        state: present
        template: "templates/create_vm.yml.j2"
      register: templatevm
      until: templatevm is succeeded
      retries: 60
      delay: 10
      failed_when: templatevm is failed or templatevm.failed

    - name: Include task to create vm
      ansible.builtin.import_tasks: tasks/create_vm_task.yml
      vars:
        vm_settings:
          - vmname: 'small'
            itype: 'u1.small'
          - vmname: 'medium'
            itype: 'u1.medium'
